<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ksd_cards"
 *
 * Auto generated by Extension Builder 2013-10-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'KSD Tageskarten',
	'description' => 'Verkauf von SBB Tageskarten',
	'category' => 'plugin',
	'author' => 'Sammy Abdel Gawwad',
	'author_email' => 's.a.gawwad@sunrise.ch',
	'author_company' => 'KSD',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>