<?php
return array(
	'BE' => array(
		'installToolPassword' => '8713fead20c2bf655e4134a9fe1aac4e',
		'versionNumberInFilename' => '0',
	),
	'DB' => array(
		'database' => 'typo3db_01',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => 'localhost',
		'username' => 'root',
	),
	'EXT' => array(
		'extListArray' => array(
			'introduction',
			'perm',
			'func',
			'filelist',
			'about',
			'version',
			'tsconfig_help',
			'context_help',
			'extra_page_cm_options',
			'impexp',
			'sys_note',
			'tstemplate',
			'tstemplate_ceditor',
			'tstemplate_info',
			'tstemplate_objbrowser',
			'tstemplate_analyzer',
			'func_wizards',
			'wizard_crpages',
			'wizard_sortpages',
			'lowlevel',
			'install',
			'belog',
			'beuser',
			'aboutmodules',
			'setup',
			'taskcenter',
			'info_pagetsconfig',
			'viewpage',
			'rtehtmlarea',
			'css_styled_content',
			't3skin',
			't3editor',
			'reports',
			'felogin',
			'form',
		),
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'de',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
			),
		),
	),
	'GFX' => array(
		'im_combine_filename' => 'composite',
		'im_path' => 'D:\\Programs\\Xampp\\ImageMagick-6.8.7-Q16\\',
		'im_path_lzw' => 'D:\\Programs\\Xampp\\ImageMagick-6.8.7-Q16\\',
		'im_useStripProfileByDefault' => '0',
	),
	'SYS' => array(
		'compat_version' => '6.1',
		'encryptionKey' => '87bce322f10914b382a08ec3dfcbb95c33527e04247c45c2d912f421fd5bf527b620315cada80dc90abc73f573a3cae9',
		'sitename' => 'Sensation',
	),
);
?>